[project]
name = 'Calendar-Overbooking-Conflict-Resolver'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.maybe-attend-speculator]
path = 'contracts/maybe-attend-speculator.clar'
clarity_version = 3
epoch = '3.2'

[contracts.meeting-escape-hatch]
path = 'contracts/meeting-escape-hatch.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
